test_that("`zip_extract_bm_pixmap()`", {
	skip_if_not(nzchar(Sys.which(Sys.getenv("R_ZIPCMD", "zip"))))
	skip_if_not_installed("bittermelon")
	dir <- setwd(tempdir())
	on.exit(setwd(dir), add = TRUE)
	z <- tempfile(fileext = ".zip")
	on.exit(unlink(z), add = TRUE)
	f <- pdf_create_blank(bg = "black")
	on.exit(unlink(f), add = TRUE)
	zip(basename(z), basename(f), flags = "-q")
	bm <- zip_extract_bm_pixmap(z, basename(f))
	expect_equal(bm[1, 1], "#000000FF")

	skip_if_not_installed("jpeg")
	skip_if_not(capabilities("jpeg"))
	f <- tempfile(fileext = ".jpg")
	on.exit(unlink(f), add = TRUE)
	grDevices::jpeg(f, bg = "black")
	grid::grid.newpage()
	invisible(dev.off())
	zip(basename(z), basename(f), flags = "-q")
	bm <- zip_extract_bm_pixmap(z, basename(f))
	expect_equal(bm[1, 1], "#000000FF")

	f <- tempfile(fileext = ".jpeg")
	on.exit(unlink(f), add = TRUE)
	grDevices::jpeg(f, bg = "black")
	grid::grid.newpage()
	invisible(dev.off())
	zip(basename(z), basename(f), flags = "-q")
	bm <- zip_extract_bm_pixmap(z, basename(f))
	expect_equal(bm[1, 1], "#000000FF")

	skip_if_not_installed("png")
	skip_if_not(capabilities("png"))
	f <- tempfile(fileext = ".png")
	on.exit(unlink(f), add = TRUE)
	grDevices::png(f, bg = "black")
	grid::grid.newpage()
	invisible(dev.off())
	zip(basename(z), basename(f), flags = "-q")
	bm <- zip_extract_bm_pixmap(z, basename(f))
	expect_equal(bm[1, 1], "#000000FF")

	skip_if_not(capabilities("tiff"))
	f <- tempfile(fileext = ".tiff")
	on.exit(unlink(f), add = TRUE)
	grDevices::tiff(f, bg = "black")
	grid::grid.newpage()
	invisible(dev.off())
	zip(basename(z), basename(f), flags = "-q")
	expect_error(zip_extract_bm_pixmap(z, basename(f)))
})
